### ISSUE TITLE
Document the AWS_DEFAULT_REGION trick

### ISSUE THREAD

**Issue by sd65** [runtheops/ssm-diff#5]
Hi,

Thanks for this great tool. We adopted entirely in our team as soon as we found a way to point ssm-diff to a specific region. As you may know, you have to run:

`AWS_DEFAULT_REGION=<your region> ssm-diff ...`

I think this should be in the README, do you agree?

**Comment by runtheops** [comment]
Hi Sylvain,

Glad that it works for you, I find the tool surprisingly convenient as well, despite its relative simplicity.
A couple of enhancements were introduced, and known bugs were fixed in a latest merged pull, thanks to @AndrewChubatiuk; will release a new version in a while, but you might want to give em a try if you spotted any problems.

Added an extra bit of info on how AWS SDK (thus, ssm-diff) figures out its configuration to README.
